[package]
name = "earthquakes-birthday"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = {version = "0.11.12", features = ["blocking", "json"]}
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
num-traits = "0.2.15"
chrono = "0.4.22"
envy = "0.4.2"
